{% set name = "PySimpleGUIWx" %}
{% set version = "0.17.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name }}-{{ version }}.tar.gz
  sha256: 910d6c1a0e472b8cef02cb9200428d55d930129eb4685106b8df0345d284e9bd

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - wxpython

test:
  imports:
    - PySimpleGUIWx

about:
  home: https://github.com/PySimpleGUI/PySimpleGUI
  license: LGPL-3.0
  license_family: LGPL
  license_file: license.txt
  summary: GUI SDK Launched in 2018 Actively developed and supported. Super-simple to create custom GUI's.
  doc_url: http://www.pysimplegui.org/
  dev_url: https://github.com/PySimpleGUI/PySimpleGUI

extra:
  recipe-maintainers:
    - silun
